# Generated by Django 5.2.17 on 2026-09-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("product_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "converted_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
            ],
        ),
    ]
